### ISSUE TITLE
Jekyll site not rendering properly

### ISSUE THREAD

**Issue by NateBaldwinDesign** [NateBaldwinDesign/aggregator#39]
*probably due to recent renaming of "Dragoman" repo to "dragoman"

CSS/assets do not properly load on the jekyll page https://natebaldwindesign.github.io/dragoman/

See branch gh-pages for jekyll page

**Comment by kushalpandya** [comment]
I can work on this. =)

**Comment by kushalpandya** [comment]
One more thing I'd suggest to add to `_config.yml` along with fixing this problem is that there are certain unnecessary files and folders (eg; `config.rb`, `Gemfile`, `Gemfile.lock` and `node_modules` ) copied over to generated `_site` folder while running `jekyll build`. This copying of extra files may further slowdown development process when you run `jekyll serve` without `--no-watch`. May be I can file separate issue to track that. Let me know what you think.

**Comment by NateBaldwinDesign** [comment]
Thank you -- I'll mark another issue for that one
